### ISSUE TITLE
Continued version

### ISSUE THREAD

**Issue by emipa606** [Shadowrabbit/SR_DarkArtist#1]
Hi
I got a request of updating your BondageBed Torture-mod on steam by a few users as the new version apparently does not work the same way as this. There is also a BondageBedTorture Furniture Addon that is not compatible with the new 1.3 version.
Would it be okay if I released an updated version of this mod? I could not find a license but saw that the new mod has a permissive licese.
Regards
Mlie

**Comment by Shadowrabbit** [comment]
Hi,


Glad to hear from you. I can't reply you by myself only, I'll ask for other partners and reply to you later.&nbsp;


Regrads.
Rabbit


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowrabbit/SR_DarkArtist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 凌晨1:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Shadowrabbit/SR_DarkArtist] Continued version (Issue #1)





 
Hi
 I got a request of updating your BondageBed Torture-mod on steam by a few users as the new version apparently does not work the same way as this. There is also a BondageBedTorture Furniture Addon that is not compatible with the new 1.3 version.
 Would it be okay if I released an updated version of this mod? I could not find a license but saw that the new mod has a permissive licese.
 Regards
 Mlie

**Comment by Shadowrabbit** [comment]
Hi, Mlie


We agree that you release the continue version.
Thank you for your contribution to the community


Regards
Rabbit
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shadowrabbit/SR_DarkArtist"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 凌晨1:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Shadowrabbit/SR_DarkArtist] Continued version (Issue #1)





 
Hi
 I got a request of updating your BondageBed Torture-mod on steam by a few users as the new version apparently does not work the same way as this. There is also a BondageBedTorture Furniture Addon that is not compatible with the new 1.3 version.
 Would it be okay if I released an updated version of this mod? I could not find a license but saw that the new mod has a permissive licese.
 Regards
 Mlie

**Comment by emipa606** [comment]
Great! I usually add the MIT license to all my published mods that do not already have a license.
If you would like another license, just ping me and Ill change it!
